language: c

compiler: gcc

before_script:
    - mkdir build/
    - cd build/
    - cmake ..

script: make

after_script:
    - ./threads

notifications:
    email:
        - jianfan.tw@gmail.com
    on_success: change
    on_failure: always